# Generated by Django 4.2.6 on 2024-02-19 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ap_app", "0002_userprofile_external_teams_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringException",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Exception_Start",
                    models.DateField(
                        default=django.utils.timezone.now,
                        max_length=200,
                        verbose_name="Date",
                    ),
                ),
                (
                    "Exception_End",
                    models.DateField(
                        default=django.utils.timezone.now,
                        max_length=200,
                        verbose_name="Date",
                    ),
                ),
                (
                    "Target_User_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "User_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurringexception",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
